version: "2"

services:
  server-node:
    build: "./docker/services/server-node"
    # override the default Dockerfile command
    command: "npm run dev"
    volumes:
      - ./src/server:/var/www/server
    ports:
      - 3001:3000
      - 9229:9229

  server-postgres:
    build: "./docker/services/postgres"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgresdata:/var/lib/postgresql/data
    # expose:
    #   - 5432 # Publishes 5432 to other containers but NOT to host machine
    ports:
      - 5433:5432

volumes:
  postgresdata:
    external: true

networks:
  NET::
  